name: Terraform PR Check
on:
  pull_request:
    branches:
      - main

jobs:
  terraform_dev_plan:
    name: Terraform Plan for dev
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file="env/dev.tfvars"

  terraform_prod_plan:
    name: Terraform Plan for prod
    needs: [terraform_dev_plan]
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: injectValues
        working-directory: terraform/env
        env:
          PUBLICCIDR: ${{ vars.PUBLICCIDR }}
          # PUBLICCIDR: ${{ secrets.PUBLICCIDR }}
        run: | 
          ls
          envsubst < prod.tfvars > prodnew.tfvars
          rm prod.tfvars
          mv prodnew.tfvars prod.tfvars
          cat prod.tfvars

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file="env/prod.tfvars"
