name: Terraform PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply Workflow
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        run: terraform fmt
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan for dev
        run: terraform plan -var-file="env/dev.tfvars"
        working-directory: ./terraform

      - name: Terraform Plan for prod
        run: terraform plan -var-file="env/prod.tfvars"
        working-directory: ./terraform
