name: Terraform PR Workflow
# on:
  # pull_request:
  #   branches:
  #     - main
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'allowed environments : dev | prod'
        required: true
      approval:
        description: 'PR approved : true | false'
        required: true


jobs:
  terraform:
    name: Terraform PR Checks
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        run: terraform fmt
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.env || 'dev' }}.tfvars"
        working-directory: ./terraform

      - name: Terraform Apply
        working-directory: ./terraform
        if: ${{ github.event.inputs.approval == 'true' }}
        run: terraform apply -var-file="${{ github.event.inputs.env || 'dev' }}.tfvars" --auto-approve
        